name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Loggin in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker images for each service
      - name: Build and push API Gateway image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and push Customer Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/customer-service:latest ./customer-services
          docker push ${{ secrets.DOCKER_USERNAME }}/customer-service:latest

      - name: Build and push Inventory Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest ./inventory-services
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest

      - name: Build and push Menu Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/menu-service:latest ./menu-services
          docker push ${{ secrets.DOCKER_USERNAME }}/menu-service:latest

      - name: Build and push Order Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-services
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      - name: Build and push Payment Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ./payment-services
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest